name: CVRanks
main: org.cubeville.cvranks.CVRanks
author: FrediW, RandomRob13
version: 0.1
api-version: 1.16

# depend: [CVTools]

commands:
  
  doc:
    description: DR rank command
    
  respawn:
    description: DM respawn command
    permission: cvranks.death.respawn

  rat:
    description: Open ratpack inventory
    permission: cvranks.death.ratpack

  ns:
    description: Nightstalker
    permission: cvranks.mining.nightstalker

  scuba:
    description: Scuba
    permission: cvranks.service.scuba

  smelt:
    description: Activate Instasmelt
    permission: cvranks.mining.instasmelt

  mason:
    description: Activate stonemason
    permission: cvranks.build.stonemason

  mg:
    description: Moss gardener
    permission: cvranks.build.mossgardener

  brick:
    description: Brick layer
    permission: cvranks.build.bricklayer

  carp:
    description: Master Carpenter command
    permission: cvranks.build.carpenter

  level:
    description: Repairman Level command
    permission: cvranks.service.repairman
    aliases: lvl
    
  rp:
    description: Repairman Repair command
    permission: cvranks.service.repairman
    aliases: repair

  mr:
    description: Minirank command

  dh:
    description: Death Hound command
    aliases: deathhound

permissions:
  cvranks.service.dr:
    description: Doctor rank
    default: op

  cvranks.death.respawn:
    description: Respawn command
    default: op

  cvranks.death.ratpack:
    description: Stores a ratpack for the player, access to /rat
    default: op

  cvranks.death.ratpack.master:
    description: Additional ratpack inventory row
    default: op

  cvranks.death.hound:
    description: Use of the deathhound command
    default: op
